In [1]:
import glob
import os
import copy

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
%load_ext autoreload
%autoreload 2

import sys
sys.path.append("..")

pd.set_option('display.max_columns', None) # Displays all columns of df

In [13]:
# Load all files from one folder

Files_dir = '/Users/abamford/Desktop/TUBB2B-KI_preliminary_analysis/Batch20230223/D55/TUBB2B-KI_D55_2%/50ms/Tracking/Run20240226/Factor5Link5'
Files_path = os.path.join(Files_dir,'*.csv') 
Files = glob.glob(Files_path)

In [20]:
Files

['/Users/abamford/Desktop/TUBB2B-KI_preliminary_analysis/Batch20230223/D55/TUBB2B-KI_D55_2%/50ms/Tracking/Run20240226/Factor5Link5/100tp_561-100-50ms-1000g_12_conf561_merged_spots_tracks.csv',
 '/Users/abamford/Desktop/TUBB2B-KI_preliminary_analysis/Batch20230223/D55/TUBB2B-KI_D55_2%/50ms/Tracking/Run20240226/Factor5Link5/100tp_561-100-50ms-1000g_9_conf561_merged_spots_tracks.csv',
 '/Users/abamford/Desktop/TUBB2B-KI_preliminary_analysis/Batch20230223/D55/TUBB2B-KI_D55_2%/50ms/Tracking/Run20240226/Factor5Link5/100tp_561-100-50ms-1000g_19_conf561_merged_spots_tracks.csv',
 '/Users/abamford/Desktop/TUBB2B-KI_preliminary_analysis/Batch20230223/D55/TUBB2B-KI_D55_2%/50ms/Tracking/Run20240226/Factor5Link5/100tp_561-100-50ms-1000g_11_conf561_merged_spots_tracks.csv',
 '/Users/abamford/Desktop/TUBB2B-KI_preliminary_analysis/Batch20230223/D55/TUBB2B-KI_D55_2%/50ms/Tracking/Run20240226/Factor5Link5/100tp_561-100-50ms-1000g_18_conf561_merged_spots_tracks.csv',
 '/Users/abamford/Desktop/TUBB2B-KI_preliminary_analysis/Batch20230223/D55/TUBB2B-KI_D55_2%/50ms/Tracking/Run20240226/Factor5Link5/100tp_561-100-50ms-1000g_23_conf561_merged_spots_tracks.csv',
 '/Users/abamford/Desktop/TUBB2B-KI_preliminary_analysis/Batch20230223/D55/TUBB2B-KI_D55_2%/50ms/Tracking/Run20240226/Factor5Link5/100tp_561-100-50ms-1000g_10_conf561_merged_spots_tracks.csv',
 '/Users/abamford/Desktop/TUBB2B-KI_preliminary_analysis/Batch20230223/D55/TUBB2B-KI_D55_2%/50ms/Tracking/Run20240226/Factor5Link5/100tp_561-100-50ms-1000g_16_conf561_merged_spots_tracks.csv',
 '/Users/abamford/Desktop/TUBB2B-KI_preliminary_analysis/Batch20230223/D55/TUBB2B-KI_D55_2%/50ms/Tracking/Run20240226/Factor5Link5/100tp_561-100-50ms-1000g_20_conf561_merged_spots_tracks.csv',
 '/Users/abamford/Desktop/TUBB2B-KI_preliminary_analysis/Batch20230223/D55/TUBB2B-KI_D55_2%/50ms/Tracking/Run20240226/Factor5Link5/100tp_561-100-50ms-1000g_13_conf561_merged_spots_tracks.csv',
 '/Users/abamford/Desktop/TUBB2B-KI_preliminary_analysis/Batch20230223/D55/TUBB2B-KI_D55_2%/50ms/Tracking/Run20240226/Factor5Link5/Batch20230223_D55_50ms.csv',
 '/Users/abamford/Desktop/TUBB2B-KI_preliminary_analysis/Batch20230223/D55/TUBB2B-KI_D55_2%/50ms/Tracking/Run20240226/Factor5Link5/100tp_561-100-50ms-1000g_8_conf561_merged_spots_tracks.csv']

In [21]:
# Read csv files into list

all_files = []

for file in Files:
    table = pd.read_csv(file)
    all_files.append(table)

all_files[0].head()

,frame,roi_id,x,y,bg_denoised,amp_denoised,sigma_y,sigma_x,mean_spot_intensity,particle,track_id,unique_id
0,0,1.0,704.188314,84.979861,1732.416267,1770.000000,1.724000,1.829084,388.111111,0,1.0_0.0,9
1,0,1.0,478.366964,450.566084,2787.282372,4865.470201,1.382217,1.153637,650.416667,1,1.0_1.0,25
2,0,1.0,470.422562,455.334819,1556.456771,3133.321718,2.774024,1.776804,486.361111,2,1.0_2.0,20
3,0,1.0,464.746104,474.741509,2235.176525,5726.910479,1.596721,1.297047,863.333333,5,1.0_5.0,18
4,0,1.0,669.220970,138.560277,1538.547137,3379.421224,3.000000,2.404281,507.194444,6,1.0_6.0,23

In [22]:
# Adds columns "line", "day" and "batch" to table

for file in all_files:
    
    # The strings need to be changed accordingly!

    line = "TUBB2B-KI"
    day = 55
    batch = "20230223"
   
    file["line"] = line
    file["day"] = day
    file["batch"] = batch
  

all_files[0].head()

,frame,roi_id,x,y,bg_denoised,amp_denoised,sigma_y,sigma_x,mean_spot_intensity,particle,track_id,unique_id,line,day,batch
0,0,1.0,704.188314,84.979861,1732.416267,1770.000000,1.724000,1.829084,388.111111,0,1.0_0.0,9,TUBB2B-KI,55,20230223
1,0,1.0,478.366964,450.566084,2787.282372,4865.470201,1.382217,1.153637,650.416667,1,1.0_1.0,25,TUBB2B-KI,55,20230223
2,0,1.0,470.422562,455.334819,1556.456771,3133.321718,2.774024,1.776804,486.361111,2,1.0_2.0,20,TUBB2B-KI,55,20230223
3,0,1.0,464.746104,474.741509,2235.176525,5726.910479,1.596721,1.297047,863.333333,5,1.0_5.0,18,TUBB2B-KI,55,20230223
4,0,1.0,669.220970,138.560277,1538.547137,3379.421224,3.000000,2.404281,507.194444,6,1.0_6.0,23,TUBB2B-KI,55,20230223

In [17]:
# Adds column "file_name"

# List of file names within the folder
file_names = os.listdir(Files_dir)

for df, file_name in zip (all_files, file_names):
    df['file_name'] = file_name

all_files[1].head()

,frame,roi_id,x,y,bg_denoised,amp_denoised,sigma_y,sigma_x,mean_spot_intensity,particle,track_id,unique_id,line,day,batch,file_name
0,0,1.0,381.385465,177.270971,1859.396528,2331.416854,1.577814,1.475139,410.361111,0,1.0_0.0,10,TUBB2B-KI,55,20230223,100tp_561-100-50ms-1000g_9_conf561_merged_spot...
1,0,1.0,417.072895,232.704841,2664.123491,11035.077314,1.286185,1.167038,1193.444444,1,1.0_1.0,2,TUBB2B-KI,55,20230223,100tp_561-100-50ms-1000g_9_conf561_merged_spot...
2,0,1.0,433.934843,258.795286,2214.036100,5978.149484,1.299000,1.371503,858.694444,2,1.0_2.0,1,TUBB2B-KI,55,20230223,100tp_561-100-50ms-1000g_9_conf561_merged_spot...
3,0,1.0,479.871573,317.129205,2895.357954,3324.924603,1.353208,1.473125,632.666667,4,1.0_4.0,3,TUBB2B-KI,55,20230223,100tp_561-100-50ms-1000g_9_conf561_merged_spot...
4,0,1.0,484.377955,323.537632,2981.410065,3778.088178,1.332051,1.201871,639.500000,5,1.0_5.0,8,TUBB2B-KI,55,20230223,100tp_561-100-50ms-1000g_9_conf561_merged_spot...

In [23]:
def create_unique_track_id(row: pd.Series, file_identifier: str) -> str:
    """
    Function to create unique track-ids for all tracks of all ROIs per image
    by combining roi_id, particle number, and file information.
    """
    return f"{file_identifier}_{row['roi_id']}_{row['particle']}"

In [24]:
# Adds column containing a unique identifier base on file name, ROI and particle

all_files_clean = []

for i, df in enumerate(all_files):

    position = 11

    # Apply unique track IDs using the create_track_id function and and remove track_id column (redundant)
    df["roi_id"] = df["roi_id"].astype(int)
    df.insert(position, 'file_roi_particle', df.apply(lambda row: create_unique_track_id(row, i), axis=1))
    df = df.drop(columns=['bg_denoised', 'amp_denoised', 'sigma_y', 'sigma_x', 'track_id'])
    df = df.sort_values(by=["file_roi_particle", "frame"])

    all_files_clean.append(df)

all_files_clean[5].head()

ValueError: cannot insert file_roi_particle, already exists

In [25]:
all_files_clean[0].head()

,frame,roi_id,x,y,mean_spot_intensity,particle,file_roi_particle,unique_id,line,day,batch
0,0,1,704.188314,84.979861,388.111111,0,0_1_0,9,TUBB2B-KI,55,20230223
18,1,1,703.994228,85.008558,392.000000,0,0_1_0,9,TUBB2B-KI,55,20230223
22,2,1,703.689525,84.904920,361.111111,0,0_1_0,9,TUBB2B-KI,55,20230223
31,3,1,704.355406,85.108401,339.472222,0,0_1_0,9,TUBB2B-KI,55,20230223
1,0,1,478.366964,450.566084,650.416667,1,0_1_1,25,TUBB2B-KI,55,20230223

In [26]:
# Output directory

output_dir = r'/Users/abamford/Desktop/TUBB2B-KI_preliminary_analysis/Batch20230223/D55/TUBB2B-KI_D55_2%/50ms/Tracking/Run20240226/Cleanfiles_Factor5Link5'

In [27]:
# Save clean tables

for table, csv_file in zip(all_files_clean, Files):
    
    # Extract the original file name without the extension
    file_name = os.path.splitext(os.path.basename(csv_file))[0]
    print(file_name)
    
    # Define the output file path
    output_file = os.path.join(output_dir, file_name + '_clean.csv')
    print(output_file)

    # Save clean table
    table.to_csv(output_file, index=False)

100tp_561-100-50ms-1000g_12_conf561_merged_spots_tracks
/Users/abamford/Desktop/TUBB2B-KI_preliminary_analysis/Batch20230223/D55/TUBB2B-KI_D55_2%/50ms/Tracking/Run20240226/Cleanfiles_Factor5Link5/100tp_561-100-50ms-1000g_12_conf561_merged_spots_tracks_clean.csv
100tp_561-100-50ms-1000g_9_conf561_merged_spots_tracks
/Users/abamford/Desktop/TUBB2B-KI_preliminary_analysis/Batch20230223/D55/TUBB2B-KI_D55_2%/50ms/Tracking/Run20240226/Cleanfiles_Factor5Link5/100tp_561-100-50ms-1000g_9_conf561_merged_spots_tracks_clean.csv
100tp_561-100-50ms-1000g_19_conf561_merged_spots_tracks
/Users/abamford/Desktop/TUBB2B-KI_preliminary_analysis/Batch20230223/D55/TUBB2B-KI_D55_2%/50ms/Tracking/Run20240226/Cleanfiles_Factor5Link5/100tp_561-100-50ms-1000g_19_conf561_merged_spots_tracks_clean.csv
100tp_561-100-50ms-1000g_11_conf561_merged_spots_tracks
/Users/abamford/Desktop/TUBB2B-KI_preliminary_analysis/Batch20230223/D55/TUBB2B-KI_D55_2%/50ms/Tracking/Run20240226/Cleanfiles_Factor5Link5/100tp_561-100-50ms-1000g_11_conf561_merged_spots_tracks_clean.csv
100tp_561-100-50ms-1000g_18_conf561_merged_spots_tracks
/Users/abamford/Desktop/TUBB2B-KI_preliminary_analysis/Batch20230223/D55/TUBB2B-KI_D55_2%/50ms/Tracking/Run20240226/Cleanfiles_Factor5Link5/100tp_561-100-50ms-1000g_18_conf561_merged_spots_tracks_clean.csv
100tp_561-100-50ms-1000g_23_conf561_merged_spots_tracks
/Users/abamford/Desktop/TUBB2B-KI_preliminary_analysis/Batch20230223/D55/TUBB2B-KI_D55_2%/50ms/Tracking/Run20240226/Cleanfiles_Factor5Link5/100tp_561-100-50ms-1000g_23_conf561_merged_spots_tracks_clean.csv
100tp_561-100-50ms-1000g_10_conf561_merged_spots_tracks
/Users/abamford/Desktop/TUBB2B-KI_preliminary_analysis/Batch20230223/D55/TUBB2B-KI_D55_2%/50ms/Tracking/Run20240226/Cleanfiles_Factor5Link5/100tp_561-100-50ms-1000g_10_conf561_merged_spots_tracks_clean.csv
100tp_561-100-50ms-1000g_16_conf561_merged_spots_tracks
/Users/abamford/Desktop/TUBB2B-KI_preliminary_analysis/Batch20230223/D55/TUBB2B-KI_D55_2%/50ms/Tracking/Run20240226/Cleanfiles_Factor5Link5/100tp_561-100-50ms-1000g_16_conf561_merged_spots_tracks_clean.csv
100tp_561-100-50ms-1000g_20_conf561_merged_spots_tracks
/Users/abamford/Desktop/TUBB2B-KI_preliminary_analysis/Batch20230223/D55/TUBB2B-KI_D55_2%/50ms/Tracking/Run20240226/Cleanfiles_Factor5Link5/100tp_561-100-50ms-1000g_20_conf561_merged_spots_tracks_clean.csv
100tp_561-100-50ms-1000g_13_conf561_merged_spots_tracks
/Users/abamford/Desktop/TUBB2B-KI_preliminary_analysis/Batch20230223/D55/TUBB2B-KI_D55_2%/50ms/Tracking/Run20240226/Cleanfiles_Factor5Link5/100tp_561-100-50ms-1000g_13_conf561_merged_spots_tracks_clean.csv

In [28]:
# To merge all tracks belonging to same timepoint into one list while maintaining unique identity of every track

merged_file = pd.concat(all_files_clean).sort_values(by=["file_roi_particle", "frame"])
merged_file.head(100)

,frame,roi_id,x,y,mean_spot_intensity,particle,file_roi_particle,unique_id,line,day,batch
0,0,1,704.188314,84.979861,388.111111,0,0_1_0,9,TUBB2B-KI,55,20230223
18,1,1,703.994228,85.008558,392.000000,0,0_1_0,9,TUBB2B-KI,55,20230223
22,2,1,703.689525,84.904920,361.111111,0,0_1_0,9,TUBB2B-KI,55,20230223
31,3,1,704.355406,85.108401,339.472222,0,0_1_0,9,TUBB2B-KI,55,20230223
1,0,1,478.366964,450.566084,650.416667,1,0_1_1,25,TUBB2B-KI,55,20230223
...,...,...,...,...,...,...,...,...,...,...,...
372,32,1,657.142057,162.997170,409.305556,130,0_1_130,26,TUBB2B-KI,55,20230223
401,35,1,656.500985,163.369326,352.416667,130,0_1_130,26,TUBB2B-KI,55,20230223
405,36,1,656.315990,164.196313,386.361111,130,0_1_130,26,TUBB2B-KI,55,20230223
421,37,1,656.798194,163.794354,609.388889,130,0_1_130,26,TUBB2B-KI,55,20230223
433,38,1,656.397861,163.553490,371.777778,130,0_1_130,26,TUBB2B-KI,55,20230223

In [30]:
# Save merged file

# Define the output file path
output_file = os.path.join(output_dir, 'Batch20230223_D55_50ms.csv')
print(output_file)

# Save merged table
merged_file.to_csv(output_file, index=False)

/Users/abamford/Desktop/TUBB2B-KI_preliminary_analysis/Batch20230223/D55/TUBB2B-KI_D55_2%/50ms/Tracking/Run20240226/Cleanfiles_Factor5Link5/Batch20230223_D55_50ms.csv