In [1]:
import napari
from tifffile import imread
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline
%load_ext autoreload
%autoreload 2

In [2]:
# Load image

image = imread('/Volumes/gchao/bamfaile/Analysis/TUBB2B-KI/Batch20230223/D21/Denoised/Masks_created/100tp_561-100-50ms-1000g_10_conf561_merged.tif')

In [43]:
print(image.dtype, image.shape, np.min(image), np.max(image))

uint16 (100, 2, 1024, 1024) 3 19716

In [9]:
# Loads image mask

image_mask = imread('/Volumes/gchao/bamfaile/Analysis/TUBB2B-KI/Batch20230223/D21/ROIs/ROIs_as_mask_BIOP/100tp_561-100-50ms-1000g_10_conf561_merged_ROIs.tif')

In [44]:
print(image_mask.dtype, image_mask.shape)

uint8 (1024, 1024)

In [5]:
# Initializes Napari viewer

viewer = napari.Viewer()

In [6]:
# Adds image to Napari viewer

viewer.add_image(image)

In [21]:
# Adds mask image to Napari viewer

viewer.add_image(image_mask,
                 colormap="gist_earth",
                 contrast_limits=[0,8],
                 opacity=0.2)

In [45]:
# Loads detected spots

spots_path = r"/Volumes/gchao/bamfaile/Analysis/TUBB2B-KI/Batch20230223/D21/Spotdetection_tracking/Spotdetection/100tp_561-100-50ms-1000g_10_conf561_merged_spots.csv"
spots = pd.read_csv(spots_path)
spots.head()

,frame,roi_id,x,y,bg_denoised,amp_denoised,sigma_y,sigma_x,mean_spot_intensity
0,0,1,431.288625,508.376685,2459.179696,9835.486839,1.340988,1.465605,996.444444
1,0,1,461.810648,510.694959,3302.619042,6497.311906,1.383798,1.511459,976.250000
2,0,1,376.434863,513.387607,2912.420122,5514.160800,1.634161,1.579335,755.722222
3,0,1,420.438108,518.015479,3081.338296,7387.487521,1.442834,1.205538,811.055556
4,0,1,336.471585,522.069075,3577.971889,4112.105070,1.641663,1.626949,745.722222

In [46]:
# Creates df that contains xyct axes in the same order as image --> tcxy

spots_tcyxcoord = spots.iloc[:, np.r_[0,3,2]]
spots_tcyxcoord.insert(1, "channel", 0)
spots_tcyxcoord

      frame  channel           y           x
0         0        0  508.376685  431.288625
1         0        0  510.694959  461.810648
2         0        0  513.387607  376.434863
3         0        0  518.015479  420.438108
4         0        0  522.069075  336.471585
...     ...      ...         ...         ...
1763     99        0  359.543293  495.431849
1764     99        0  269.505765  809.600904
1765     99        0  286.466109  799.463527
1766     99        0  294.162258  799.162983
1767     99        0  386.608975  830.755366

[1768 rows x 4 columns]

:

In [34]:
spots_tcyxcoord

      frame  channel           y           x
0         0        0  508.376685  431.288625
1         0        0  510.694959  461.810648
2         0        0  513.387607  376.434863
3         0        0  518.015479  420.438108
4         0        0  522.069075  336.471585
...     ...      ...         ...         ...
1763     99        0  359.543293  495.431849
1764     99        0  269.505765  809.600904
1765     99        0  286.466109  799.463527
1766     99        0  294.162258  799.162983
1767     99        0  386.608975  830.755366

[1768 rows x 4 columns]

In [35]:
# Creats array from df (necessary to use in the points layer of Napari)

spots_tcyxarray = spots_tcyxcoord.to_numpy()
spots_tcyxarray

array([[  0.        ,   0.        , 508.3766853 , 431.28862462],
       [  0.        ,   0.        , 510.69495937, 461.81064794],
       [  0.        ,   0.        , 513.38760678, 376.43486264],
       ...,
       [ 99.        ,   0.        , 286.46610902, 799.46352699],
       [ 99.        ,   0.        , 294.16225846, 799.16298307],
       [ 99.        ,   0.        , 386.60897465, 830.75536647]])

In [42]:
# Adds detected spots to points layer

viewer.add_points(spots_tcyxcoord,
                  face_color='#ffffff00',
                  edge_color='magenta')